---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: test-ilab15
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-ilab15 
  name: test-ilab15
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi